Make Django models
shoishizaki/employee_manage_web_app pull request #4
Opened 2019-07-17 06:13 UTC by shoishizaki

@ryotogashi 　Djangoでのmodelを作成しましたので確認お願いします。

2019-07-17 17:14 UTC, ryonryon requested changes

2019-07-17 17:14 UTC, ryotogashi commented on employee_management/model/employee_model.py
> +    phone = models.CharField(max_length=200)
phone number は数値がいいんじゃないかと思います。

2019-07-18 02:41 UTC, shoishizaki commented
@ryotogashi  modelを数値代入のものに変更したしたので、確認お願いします。

2019-07-19 21:15 UTC, ryonryon approved these changes
@shoishizaki lgtm

2019-07-19 21:15 UTC, ryotogashi commented on employee_management/model/employee_model.py
> +    phone = models.BigIntegerField()
👍

こんなページ見つけたので参考までに
https://qiita.com/nachashin/items/f768f0d437e0042dd4b3

2019-07-19 22:57 UTC, merged